version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/env.local
    depends_on:
      - mongo
    ports:
      - '5000:5000'

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./ai-service/env.local
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'

volumes:
  mongo-data:
